name: botanicabay
description: "Never forget to water your green friends. Let us be your plant watering reminder."
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter_launcher_icons:
  android: true
  image_path: "assets/appIcon.png"

flutter_native_splash:
  color: "#E4E5F1"
  color_dark: "#121212"
  image: assets/appIcon.png
  image_dark: assets/appIcon.png

  android_12:
    color: "#E4E5F1"
    color_dark: "#121212"
    image: assets/appSplash12.png
    image_dark: assets/appSplash12.png

flutter:
  uses-material-design: true
  
  assets:
    - assets/